config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'

  resources :users
  resources :gossips do
    resources :reviews
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

  has_many :users

  validates :zip_code, length: { maximum: 15 }, format: { with: /[[:digit:]]/, message: 'Number Only' }
  validates :name, presence: true

end

app/models/gossip.rb
class Gossip < ApplicationRecord

  belongs_to :user

  has_many :tags, through: :join_tags
  has_many :reviews
  has_many :likes

  validates :title, presence: true, length: { in: 3..54 }
  validates :content, presence: true

end

app/models/join_pm.rb
class JoinPm < ApplicationRecord

	belongs_to :private_message
	belongs_to :user

end

app/models/join_tag.rb
class JoinTag < ApplicationRecord

	belongs_to :gossip
	belongs_to :tag

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :gossip

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

  belongs_to :sender, class_name: "User"

  has_many :recipients, class_name: "User", through: :join_pms

  validates :content, presence: true

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :gossip

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :potins, through: :join_tags

  validates :title, presence: true, length: { maximum: 30 }

end

app/models/user.rb
class User < ApplicationRecord

  belongs_to :city

  has_many :reviews
  has_many :gossips
  has_many :sent_messages, class_name: "PrivateMessage"
  has_many :received_messages, class_name: "PrivateMessage", through: :join_pms
  has_many :likes

  has_secure_password

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :age, length: { is: 2 }, format: { with: /[[:digit:]]/, message: 'Number Only' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
    @review = Review.new
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.user_id = current_user.id
    if @gossip.save
      flash.notice = "Gossip Created"
      redirect_to @gossip
    else
      @gossip.errors.full_messages.each do |message|
        flash.alert = "Error #{message}"
      end
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    if @gossip.save
      flash.notice = "Gossip Updated"
      redirect_to @gossip
    else
      @gossip.errors.full_messages.each do |message|
        flash.alert = "Error #{message}"
      end
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.delete
    flash.notice = "Gossip Destroyed"

    redirect_to root_path
  end


  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @gossips = Gossip.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    # @review = Review.new(review_params)
    @review = @gossip.reviews.build(review_params)
    @review.user_id = current_user.id
    if @review.save
      flash.notice = 'comment added'
      redirect_to @gossip
    else
      flash.notice = 'error'
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @review = Review.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:gossip_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash.notice = 'comment changed'
      redirect_to @gossip
    else
      flash.notice = 'error'
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @review = @gossip.reviews.find(params[:id]).delete
    redirect_to @gossip
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # cherche s'il existe un utilisateur en base avec l’e-mail
    user = User.find_by(email: params[:session][:email])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas
      flash.notice = 'Connected'
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash.notice = 'User Created'
      redirect_to @user
    else
      flash.notice = "Error : #{@user.errors.messages}"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :password, :city_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<h1>Edit Potin</h1>

<%= form_tag url_for(action: 'update'), method: "put" do %>

  <%= label_tag 'Title' %>
  <%= text_field_tag 'gossip[title]', @gossip.title %>
  <br /> <br />

  <%= label_tag 'Content' %>
  <%= text_area_tag 'gossip[content]', @gossip.content %>
  <br /> <br />

  <%= submit_tag "Update Gossip" %>

<% end %>

app/views/gossips/new.html.erb
<h1>New Potin</h1>

<%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag 'Title' %>
  <%= text_field_tag 'gossip[title]', @gossip.title %>
  <br /> <br />

  <%= label_tag 'Content' %>
  <%= text_area_tag 'gossip[content]', @gossip.content %>
  <br /> <br />

  <%= submit_tag "Create Gossip" %>

<% end %>

app/views/gossips/show.html.erb
<div class="columns is-mobile is-centered">
  <div class="card is-centered column is-half is-mobile is-centered">
    <div class="card-content">
      <p class="title">
        <%= @gossip.title %>
      </p>
      <p class="subtitle">
        Auteur : <%= link_to user_path(@gossip.user) do%><%=@gossip.user.first_name + ' ' +   @gossip.user.last_name%><%end%>
      </p>
      <p><%= @gossip.content%></p>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
      <span>
        <%= link_to 'Edit', edit_gossip_path %>
      </span>
      </p>
      <p class="card-footer-item">
      <span>
        <%= link_to 'Delete', @gossip, method: :delete %>
      </span>
      </p>


    </footer>
  </div>
</div>

<%= link_to 'Creer un commentaire', new_gossip_review_path(@gossip) %>
<div class="container m-6  columns is-mobile is-multiline is-centered">
  <% @gossip.reviews.each do |review| %>
    <div class="card m-3 column is-half is-mobile is-centered">
      <div class="card-content">
        <p class="title">
          <%= review.content%>
        </p>
      </div>
      <footer class="card-footer">
        <p class="card-footer-item">
      <span>
        <%= link_to 'Update', edit_gossip_review_path(@gossip, review) %>
      </span>
        </p>
        <p class="card-footer-item">
      <span>
        <%= link_to 'Delete', gossip_review_path(@gossip, review), method: :delete %>
      </span>
        </p>
      </footer>
    </div>
  <% end %>
</div>

<!-- app/views/posts/show.html.erb -->

<%#= form_tag gossip_review_path(@gossip.id, review.id), method: "delete" do %>
  <%#= submit_tag "Delete Comment" %>
<%# end %>

<%= form_tag gossip_reviews_path(@gossip.id) do %>


  <%= label_tag 'content' %>
  <%= text_field_tag 'review[content]', @review.content %>
  <br /> <br />

  <%= submit_tag "Add Comment" %>
<% end %>

app/views/reviews/edit.html.erb
<%= form_tag gossip_review_path(@gossip.id), method: :put do %>


  <%= label_tag 'content' %>
  <%= text_field_tag 'review[content]', @review.content %>
  <br /> <br />

  <%= submit_tag "Edit Comment" %>
<% end %>
<%= select_tag 'ville', options_from_collection_for_select(City.all, 'id','name', 2) %>
<%= select_tag 'ville', options_from_collection_for_select(City.all, 'id','name', 4) %>

app/views/users/new.html.erb
<%= form_tag @user do %>

  <%= label_tag 'Prenom' %>
  <%= text_field_tag 'user[first_name]', @user.first_name %>
  <br>
  <%= label_tag 'Nom' %>
  <%= text_field_tag 'user[last_name]', @user.last_name %>
  <br>

  <%= label_tag 'Description' %>
  <%= text_field_tag 'user[description]', @user.description %>
  <br>

  <%= label_tag 'Email' %>
  <%= text_field_tag 'user[email]', @user.email %>
  <br>

  <%= label_tag 'Age' %>
  <%= text_field_tag 'user[age]', @user.age %>
  <br>

  <%= label_tag 'password'%>
  <%= text_field_tag 'user[password]', @user.password %>
  <br>

  <%= label_tag 'City' %>
  <%= select_tag 'user[city_id]', options_from_collection_for_select(City.all, 'id', 'name') %>

  <br>
  <%= submit_tag "Sign up" %>
<% end %>

hello

app/views/users/show.html.erb
<div class="columns is-mobile is">
  <div class="card is-centered column is-half is-mobile is-centered">
    <div class="card-content">
      <p class="title">
        <%= @user.first_name %> <%= @user.last_name %>
      </p>
      <p class="subtitle">
        <%= %>
      </p>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
      <span>
        View on <a href="https://twitter.com/codinghorror/status/506010907021828096">Twitter</a>
      </span>
      </p>

    </footer>
  </div>
</div>