config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'

  resources :users
  resources :gossips do
    resources :reviews
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

  has_many :users

  validates :zip_code, length: { maximum: 15 }, format: { with: /[[:digit:]]/, message: 'Number Only' }
  validates :name, presence: true

end

app/models/gossip.rb
class Gossip < ApplicationRecord

  belongs_to :user

  has_many :tags, through: :join_tags
  has_many :reviews
  has_many :likes

  validates :title, presence: true, length: { in: 3..54 }
  validates :content, presence: true

end

app/models/join_pm.rb
class JoinPm < ApplicationRecord

	belongs_to :private_message
	belongs_to :user

end

app/models/join_tag.rb
class JoinTag < ApplicationRecord

	belongs_to :gossip
	belongs_to :tag

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :gossip

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

  belongs_to :sender, class_name: "User"

  has_many :recipients, class_name: "User", through: :join_pms

  validates :content, presence: true

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :gossip

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :potins, through: :join_tags

  validates :title, presence: true, length: { maximum: 30 }

end

app/models/user.rb
class User < ApplicationRecord

  belongs_to :city

  has_many :reviews
  has_many :gossips
  has_many :sent_messages, class_name: "PrivateMessage"
  has_many :received_messages, class_name: "PrivateMessage", through: :join_pms
  has_many :likes

  has_secure_password

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :age, length: { is: 2 }, format: { with: /[[:digit:]]/, message: 'Number Only' }

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
    @review = Review.new
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.user_id = current_user.id
    if @gossip.save
      flash.notice = "Gossip Created"
      redirect_to @gossip
    else
      @gossip.errors.full_messages.each do |message|
        flash.alert = "Error #{message}"
      end
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    if @gossip.save
      flash.notice = "Gossip Updated"
      redirect_to @gossip
    else
      @gossip.errors.full_messages.each do |message|
        flash.alert = "Error #{message}"
      end
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.delete
    flash.notice = "Gossip Destroyed"

    redirect_to root_path
  end


  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @gossips = Gossip.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    # @review = Review.new(review_params)
    @review = @gossip.reviews.build(review_params)
    @review.user_id = current_user.id
    if @review.save
      flash.notice = 'comment added'
      redirect_to @gossip
    else
      flash.notice = 'error'
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @review = Review.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:gossip_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash.notice = 'comment changed'
      redirect_to @gossip
    else
      flash.notice = 'error'
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @review = @gossip.reviews.find(params[:id]).delete
    redirect_to @gossip
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash.notice = 'User Created'
      redirect_to @user
    else
      flash.notice = "Error : #{@user.errors.messages}"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :password, :city_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheGossipProject</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'shared/navbar' %>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<%= link_to 'Creer un potin', new_gossip_path %>
<div class="container m-6  columns is-mobile is-multiline is-centered">
  <% @gossips.each do |gossip| %>
    <div class="card m-3 column is-half is-mobile is-centered">
      <div class="card-content">
        <p class="title">
          <%= gossip.title %>
        </p>
        <p class="subtitle">
          <%= gossip.content %>
        </p>
      </div>
      <footer class="card-footer">
        <p class="card-footer-item">
      <span>
        <%= link_to 'View more', gossip_path(gossip) %>
      </span>
        </p>
        <p class="card-footer-item">
      <span>
        Auteur : <%= link_to user_path(gossip.user) do%><%=gossip.user.first_name + ' ' +   gossip.user.last_name%><%end%>
      </span>
        </p>
      </footer>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>
    <% u = User.find_by(id: session[:user_id]) %>
    <h2>Bienvenue <%= u ? u.first_name: u %> !</h2>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">

            <strong>

              <%= link_to 'Sign up', new_user_path, class:'button is-primary' %>

            </strong>
          <%= link_to 'Login', new_session_path, class:'button is-light' %>
          <%= link_to 'Logout', session_path(session.id), class:'button is-light', method: :delete %>

        </div>
      </div>
    </div>
  </div>
</nav>